Path update/fix.

diff --git a/bin/JCECheck b/bin/JCECheck
--- a/bin/JCECheck
+++ b/bin/JCECheck
@@ -1,11 +1,35 @@
-#!/bin/bash
+#!/usr/bin/env sh
 
 #cd `dirname $0`
 
-CMD_CP=/usr/local/hdfs-cli/lib/hdfs-cli-full-bin.jar
+APP_DIR=`dirname $0`
 
-CLI_CMD="java -cp ${CMD_CP} JCECheck"
+PRG_ARGS=
+CMD_CP=
 
-echo ${CLI_CMD}
+if [ -f ./hadoop-cli-full-bin.jar ]; then
+    # Look in Current Directory
+    CMD_CP=$APP_DIR/hadoop-cli-full-bin.jar
+    #echo "Using bin from same directory"
+elif [ -f $APP_DIR/../target/hadoop-cli-full-bin.jar ]; then
+    # Look in ../target
+    CMD_CP=$APP_DIR/../target/hadoop-cli-full-bin.jar
+    #echo "Using bin from build directory"
+else
+    # Look in /usr/local/hadoop-cli/lib
+    if [ -f /usr/local/hadoop-cli/lib/hadoop-cli-full-bin.jar ]; then
+        CMD_CP=/usr/local/hadoop-cli/lib/hadoop-cli-full-bin.jar
+        #echo "Using bin from installation directory"
+    else
+        #echo "Couldn't locate Hadoop Cli Library"
+        exit 1
+    fi
+fi
+
+AUTO=false
+
+CLI_CMD=""
+
+CLI_CMD="${CLI_CMD}java -cp ${CMD_CP} JCECheck"
 
 eval "${CLI_CMD}"
